import { useEffect, useRef } from 'react';
import type { UnitTestReportFormat, UnitTestRun } from '@cqp/core';
import {
  downloadUnitTestReport,
  useGenerateUnitTestReport,
  useUnitTestReports,
} from '../api/hooks.js';

const FORMATS: UnitTestReportFormat[] = ['json', 'html', 'pdf', 'xlsx'];

/** Auto-generated once a run completes (docs/adr/0034) — no click needed for this one format. */
const AUTO_GENERATED_FORMAT: UnitTestReportFormat = 'xlsx';

interface UnitTestReportActionsProps {
  runId: string;
  runStatus?: UnitTestRun['status'];
}

export function UnitTestReportActions({ runId, runStatus }: UnitTestReportActionsProps) {
  const reportsQuery = useUnitTestReports(runId);
  const generate = useGenerateUnitTestReport(runId);
  const hasAutoGenerated = useRef(false);

  const existing = new Map((reportsQuery.data ?? []).map((r) => [r.format, r]));

  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (runStatus !== 'completed') return;
    if (reportsQuery.data === undefined) return; // wait for the real list before deciding
    if (existing.has(AUTO_GENERATED_FORMAT)) return; // already generated (this session or a previous one)

    hasAutoGenerated.current = true;
    generate.mutate(AUTO_GENERATED_FORMAT);
    // Only re-check when the run reaches completed or the reports list itself changes — not on every render.
  }, [runStatus, reportsQuery.data]);

  return (
    <div className="flex flex-wrap gap-2">
      {FORMATS.map((format) => {
        const report = existing.get(format);
        return (
          <div key={format} className="flex items-center gap-1 rounded border px-2 py-1 text-sm">
            <span className="uppercase text-neutral-600">{format}</span>
            <button
              onClick={() => generate.mutate(format)}
              disabled={generate.isPending}
              className="text-blue-600 hover:underline disabled:opacity-50"
            >
              {report ? 'Regenerate' : 'Generate'}
            </button>
            {report && (
              <button
                onClick={() => downloadUnitTestReport(report)}
                className="text-blue-600 hover:underline"
              >
                Download
              </button>
            )}
          </div>
        );
      })}
    </div>
  );
}
