import { describe, expect, it } from 'vitest';
import {
  InMemoryCoverageFileResultRepository,
  InMemoryCoverageReportRepository,
  InMemoryCoverageRunRepository,
  InMemoryObjectStorage,
  InMemoryRepoRepository,
} from './testing/index.js';
import { GenerateCoverageReportUseCase } from './generate-coverage-report.use-case.js';
import { GetCoverageRunUseCase } from './get-coverage-run.use-case.js';
import { GetCoverageReportUseCase } from './get-coverage-report.use-case.js';
import { GetCoverageReportContentUseCase } from './get-coverage-report-content.use-case.js';

async function setUp() {
  const repoRepository = new InMemoryRepoRepository();
  const coverageRunRepository = new InMemoryCoverageRunRepository();
  const coverageFileResultRepository = new InMemoryCoverageFileResultRepository();
  const coverageReportRepository = new InMemoryCoverageReportRepository();
  const objectStorage = new InMemoryObjectStorage();

  const repo = await repoRepository.create({ orgId: 'org_1', name: 'sample-repo' });
  const run = await coverageRunRepository.create({
    orgId: 'org_1',
    repoId: repo.id,
    baseRef: 'main',
  });
  await coverageRunRepository.updateStatus('org_1', run.id, 'running');
  await coverageRunRepository.updateResultsSummary('org_1', run.id, {
    testsTotal: 1,
    testsPassed: 1,
    testsFailed: 0,
    changedLinesTotal: 2,
    uncoveredLinesTotal: 1,
    gatePassed: false,
  });
  await coverageRunRepository.updateStatus('org_1', run.id, 'completed');

  await coverageFileResultRepository.saveMany(run.id, [
    { filePath: 'src/math.ts', changedLines: [4, 5], uncoveredLines: [5], status: 'uncovered' },
  ]);
  // Belongs to a different run — must not leak into this run's report.
  await coverageFileResultRepository.saveMany('run_other', [
    { filePath: 'unrelated.ts', changedLines: [1], uncoveredLines: [], status: 'covered' },
  ]);

  const useCase = new GenerateCoverageReportUseCase(
    new GetCoverageRunUseCase(coverageRunRepository),
    coverageFileResultRepository,
    coverageReportRepository,
    objectStorage,
  );

  return { run, useCase, coverageReportRepository, objectStorage };
}

describe('GenerateCoverageReportUseCase', () => {
  it('generates a JSON report scoped to the given run only and persists it', async () => {
    const { run, useCase, coverageReportRepository, objectStorage } = await setUp();

    const report = await useCase.execute('org_1', run.id, 'json');

    expect(report.coverageRunId).toBe(run.id);
    expect(report.format).toBe('json');
    expect(report.storageKey).toBe(`coverage-reports/org_1/${run.id}/json.json`);

    const persisted = await coverageReportRepository.findById('org_1', report.id);
    expect(persisted).not.toBeNull();

    const content = JSON.parse((await objectStorage.get(report.storageKey)).toString('utf-8'));
    expect(content.fileResults).toHaveLength(1); // math.ts — not the "run_other" result
    expect(
      content.fileResults.every((r: { filePath: string }) => r.filePath !== 'unrelated.ts'),
    ).toBe(true);
    expect(content.run.gatePassed).toBe(false);
  });

  it('generates a real HTML report end to end', async () => {
    const { run, useCase, objectStorage } = await setUp();
    const report = await useCase.execute('org_1', run.id, 'html');
    const html = (await objectStorage.get(report.storageKey)).toString('utf-8');
    expect(html).toContain('<!doctype html>');
    expect(html).toContain('src/math.ts');
  });

  it('generates a real PDF report end to end', async () => {
    const { run, useCase, objectStorage } = await setUp();
    const report = await useCase.execute('org_1', run.id, 'pdf');
    const buffer = await objectStorage.get(report.storageKey);
    expect(buffer.subarray(0, 5).toString('ascii')).toBe('%PDF-');
  });

  it('regenerating the same format for the same run upserts rather than duplicating', async () => {
    const { run, useCase, coverageReportRepository } = await setUp();

    const first = await useCase.execute('org_1', run.id, 'html');
    const second = await useCase.execute('org_1', run.id, 'html');

    expect(second.id).toBe(first.id);
    const all = await coverageReportRepository.listByRun('org_1', run.id);
    expect(all.filter((r) => r.format === 'html')).toHaveLength(1);
  });

  it('rejects a runId that does not exist', async () => {
    const { useCase } = await setUp();
    await expect(useCase.execute('org_1', 'no-such-run', 'json')).rejects.toThrow(
      'CoverageRun not found',
    );
  });
});

describe('GetCoverageReportContentUseCase', () => {
  it('returns the report metadata plus the real generated bytes', async () => {
    const { run, useCase, objectStorage } = await setUp();
    const report = await useCase.execute('org_1', run.id, 'json');

    const contentUseCase = new GetCoverageReportContentUseCase(
      new GetCoverageReportUseCase(new InMemoryCoverageReportRepository([report])),
      objectStorage,
    );
    const result = await contentUseCase.execute('org_1', report.id);

    expect(result.report.id).toBe(report.id);
    expect(JSON.parse(result.content.toString('utf-8')).run.id).toBe(run.id);
  });
});
